#%RAML 1.0 Library
types:
  get_single:
    type: array
    items:
      properties:
        last_modified_date: string
        id: string
        phone: string
        name: string
        email: string
        date_of_birth: string
        gender: string
        address: string

